import Layout from "../../components/Layout"
import SideNavBar from "../../components/SideNavBar"
import Head from "next/head"
import { Spacer, Center, Heading, Image, Box, Flex, Wrap, WrapItem, Grid, GridItem, Link, Button, border, Gap, SimpleGrid } from "@chakra-ui/react"
import Colour from "../../color/napalearncolor"
import { useState } from "react"
import { Howl, Howler } from 'howler'
import Pomodoro from "../../components/Pomodoro"

let line = {
  width: '100%',
  height: '2px',
  bgColor: Colour.Darkblue,
  marginTop: '12px',
  marginBottom: '12px',
}

let key = {
  width: '96px',
  height: '96px',
  bgColor: '#DC3535',
  marginTop: '36px',
  marginLeft: '18px',
  marginRight: '18px',
}

export default function drum() {

  const boom = new Howl({
    src: ['/sounds/boom.wav'],
    autoplay: false,
  });
  {/* var clap = new Howl({ src: ['/sounds/clap.wav'] });
  var hihat = new Howl({ src: ['/sounds/hihat.wav'] });
  var kick = new Howl({ src: ['/sounds/kick.wav'] });
  var openhat = new Howl({ src: ['/sounds/openhat.wav'] });
  var ride = new Howl({ src: ['/sounds/ride.wav'] });
  var snare = new Howl({ src: ['/sounds/snare.wav'] });
  var tink = new Howl({ src: ['/sounds/tink.wav'] });
  var tom = new Howl({ src: ['/sounds/tom.wav'] });*/}

  return (
    <div>
      <Head>
        <title>Nap A Learn Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Layout>
        <div className="p-4 mt-1">
          <Heading size='2xl'>Drum Therapy</Heading>
          <Box sx={line}></Box>
          <Pomodoro />
          <SimpleGrid spacing={10}>
            <Center>
              <Button sx={key} onclick={boom.play()}> Boom </Button>
              {/*<Button sx={key} onclick={clap.play()}> Clap </Button>
              <Button sx={key} onclick={hihat.play()}> Hihat </Button>
              <Button sx={key} onclick={kick.play()}> Kick </Button>
              <Button sx={key} onclick={openhat.play()}> Openhat </Button>
              <Button sx={key} onclick={ride.play()}> Ride </Button>
              <Button sx={key} onclick={snare.play()}> Snare </Button>
              <Button sx={key} onclick={tink.play()}> Tink </Button>
              <Button sx={key} onclick={tom.play()}> Tom </Button>*/}
            </Center>
          </SimpleGrid>
        </div>
      </Layout>
    </div>
  )
}

