import { Box, Button, Center, Flex, Grid, GridItem, Heading, Image, Text, Wrap } from '@chakra-ui/react';
import Head from "next/head";
import NextLink from "next/link";
import React from 'react';
import Colour from "../color/napalearncolor";
import Header from "../components/HeaderIndex.js";

export default function Index() {

  let bgColor = {
    width: '100%',
    height: '100%',
    bgColor: Colour.CreamP,
  }
  let container = {
    width: '100%',
    marginTop: '24px',
    padding: '12px',
    align: "center",
    justify: "center"
  }
  let container1 = {
    width: '100%',
    marginTop: '30px',
    paddingLeft: '24px',
    paddingRight: '24px',
  }
  let pinkbutton = {
    backgroundColor: '#FE979B'
  }
  let boxText = {
    minWidth: '200px',
    maxWidth: '800px',
    align: 'center',
    padding: '12px',
    marginTop: '30px',
  }
  let boxContent = {
    width: '300px',
    align: 'center',
    padding: '12px',
  }
  let boxContent1 = {
    maxWidth: '270px',
    minWidth: '200px',
    backgroundColor: 'white',
    align: 'center',
    justify: 'center',
    padding: '12px',
    boxShadow: 'md',
    rounded: 'md',
    marginTop: '18px',
  }
  let boxProfile = {
    maxwidth: '270px',
    minWidth: '200px',
    align: 'center',
    justify: 'center',
    padding: '12px',
  }


  return (
    <div className="h-full flex items-center justify-center">
      <Head>
        <title>Nap A Learn Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>

      <Box sx={bgColor} >
        <Header />
        <Flex align="center" justify="center">
          <Box sx={container} align="center" justify="center">
            <Box sx={container1} align="center" justify="center">
              <Box>
                <Image src='/image/Nap_a_learn_LOGO.png' />
              </Box>
              <Heading as='h2' size='2xl' marginBottom='40px' minWidth='400px'>
                ยินดีต้อนรับสู่ Nap a Learn
              </Heading>
              <Heading as='h2' size='xl' minWidth='400px'>
                งีบก่อน เรียนทีหลัง :-)
              </Heading>
            </Box>
            <Box sx={boxText} align="center" justify="center">
              <Heading as='h2' size='xl' minWidth='200px'>
                “Nap a Learn” เป็นเว็บไซต์ที่มีจุดประสงค์เพื่อการศึกษาหาความรู้ ทั้งในทางปฏิบัติ และในทางความรู้ติดตัว นอกจากนั้นแล้ว ผู้ใช้เว็บไซต์ของพวกเรายังสามารถติดตามผลงานการเรียนรู้ต่างๆของตนเอง เพื่อประสิทธิภาพที่ดีที่สุดของการเรียนอีกด้วย</Heading>
            </Box>
            <Center>
              <NextLink href="/login" passHref>
                <Button colorScheme='' size='lg' sx={pinkbutton} marginTop='40px' marginBottom='20px' _hover={{
                  bg: 'White',
                  border: '2px solid',
                  color: Colour.FirstPink
                }}> มาเริ่มกันเลย ! </Button>
              </NextLink>
            </Center>
          </Box>
        </Flex>

        <Flex align="center" justify="center">
          <Box align="center" justify="center">
            <Box><Image src='/image/bear.png' width={300} height={300} /></Box>
            <Box><Heading as='h2' size='xl' marginTop='12px' marginBottom='12px' color='#3E3C6E'>
              มาดูกันว่า
            </Heading></Box>
            <Box><Heading as='h2' size='xl' marginBottom='60px' color='#3E3C6E'>
              Nap a Learn ทำอะไรได้บ้าง?
            </Heading></Box>
          </Box>
        </Flex>

        <Wrap spacing="30px" justify="center">
          <Flex sx={boxContent}>
            <Box align="center" justify="center">
              <Box>
                <Image marginBottom='20px' src='/image/QuestionaireMini.png' />
                <Text fontSize='4xl' color='#3E3C6E' fontWeight='bold'> Questionaire</Text>
              </Box>
              <Flex sx={boxContent1}>
                <Text textAlign='center' padding='12px'>“Questionaire” เป็นฟีเจอร์์ที่ถูกจัดทำขึ้นเพื่อเป็นแบบ
                  ทดสอบความพิการของผู้ใช้งาน เช่น ผู้พิการทางด้านสมองหรือผู้พิการ
                  ออทิสติค เป็นต้น เมื่อทำแบบสอบถามเสร็จเรียบร้อยแล้ว ระบบจะทำการประเมินว่าผู้ใช้งานเว็บไซต์นั้นเข้าข่ายความพิการด้านไหน
                  และเว็บไซต์จะนำความพิการนั้นไปปรับเนื้อหาการเรียนรู้ให้เหมาะสมกับผู้ใช้งานต่อไป</Text>
              </Flex>
            </Box>
          </Flex>

          <Flex sx={boxContent}>
            <Box align="center" justify="center">
              <Box>
                <Image marginBottom='20px' src='/image/LearningMaterialMini.png' />
                <Text fontSize='4xl' color='#3E3C6E' fontWeight='bold'> Learning Materials</Text>
              </Box>
              <Flex sx={boxContent1}>
                <Text textAlign='center' padding='12px'> “Learning Materials” เป็นฟีเจอร์ ที่ถูกจัดทำขึ้นเพื่อเสริมสร้างการเรียนรู้ของผู้ใช้งาน โดยจะแบ่งส่วนของฟีเจอร์ออกเป็นสอง
                  ส่วนซึ่งก็คือ article และ material ซึ่งในส่วนของ article จะเป็นบทความเกี่ยวกับความรู้ต่างๆ เช่น วิธีการปรับบุคลิกภาพ เป็นต้น
                  ในส่วนของ material จะเป็นรูปแบบการเรียนรู้ที่มีปฏิสัมพันธ์กับสิ่งที่เรียน เช่น การเล่นเกมปลูกผัก เพื่อให้ได้ความรู้การทำสวน เป็นต้น</Text>
              </Flex>
            </Box>
          </Flex>

          <Flex sx={boxContent}>
            <Box align="center" justify="center">
              <Box>
                <Image marginBottom='20px' src='/image/ProfessionalSkillMini.png' />
                <Text fontSize='4xl' color='#3E3C6E' fontWeight='bold'> Professional Skills</Text>
              </Box>
              <Flex sx={boxContent1}>
                <Text textAlign='center' padding='12px'> “Professional Skills” เป็นฟีเจอร์ ที่ถูกจัดทำขึ้นเพื่อเสริมสร้างการเรียนรู้ในรูปแบบของวิชาชีพ โดยจะแบ่งส่วนของฟีเจอร์ออกเป็น
                  สองส่วนซึ่งก็คือ article และ workshop ซึ่งในส่วนของ article จะเป็นบทความเกี่ยวกับการเรียนรู้ที่เกี่ยวกับวิชาชีพ เช่น การปลูกผัก
                  เป็นต้น ในส่วนของ workshop จะเป็นคลิป หรือ วิธีทำให้ทำตาม เช่น การผัดข้าวผัด เป็นต้น</Text>
              </Flex>
            </Box>
          </Flex>

          <Flex sx={boxContent}>
            <Box align="center" justify="center">
              <Box>
                <Image marginBottom='20px' src='/image/MusicTherapyMini.png' />
                <Text fontSize='4xl' color='#3E3C6E' fontWeight='bold'>  Music Therapy</Text>
              </Box>
              <Flex sx={boxContent1}>
                <Text textAlign='center' padding='12px'>  “Music Therapy” เป็นฟีเจอร์ ที่ถูกจัดทำขึ้นเพื่อเสริมสร้างความรู้สึกของผู้ใช้งาน ให้เกิดอารมณ์สุนทรีย์ และผ่อนคลายมากขึ้น
                  นอกจากนั้นผู้ใช้งานยังสามารถเล่นดนตรี ตามแบบฝึกหัดง่ายๆ ที่มีอยู่ในเว็บไซต์อีกด้วย โดยเครื่องดนตรีจะมีให้เลือกอย่างหลากหลาย
                  เช่น กลอง กีตาร์ เป็นต้น</Text>
              </Flex>
            </Box>
          </Flex>
        </Wrap>


        <Box sx={container} align="center" justify="center">
          <Heading marginTop='48px' color='#3E3C6E' > มาพัฒนาตัวเองไปกับพวกเรา! </Heading>
          <Box marginTop='60px'>
            <Image src='/image/workshop.png' width={1200} />
          </Box>
        </Box>

        <Box sx={container} align="center" justify="center">
          <Heading marginTop='48px' marginBottom='48px' color='black' > ทีมผู้จัดทำ </Heading>
        </Box>

        <Wrap spacing="30px" justify="center" marginBottom='60px'>
          <Box sx={boxProfile} align="center" justify="center">
            <Image
              borderRadius='full'
              boxSize='200px'
              src='/image/witchayut.jpg'
              minWidth='200px'
            />
            <Heading marginTop='32px' marginBottom='5px'>
              วิชยุฒม์ ช่วยชูกูล
            </Heading>
            <Text as='b' fontSize='2xl'>63070501057</Text>
          </Box>
          <Box sx={boxProfile} align="center" justify="center">
            <Image
              borderRadius='full'
              boxSize='200px'
              src='/image/sirawit2.jpg'
              minWidth='200px'
            />
            <Heading marginTop='32px' marginBottom='5px'>
              สิรวิชญ์ วัฒโน
            </Heading>
            <Text as='b' fontSize='2xl'>63070501071</Text>
          </Box>
          <Box sx={boxProfile} align="center" justify="center">
            <Image
              borderRadius='full'
              boxSize='200px'
              src='/image/siriwat2.jpg'
              minWidth='200px'
            />
            <Heading marginTop='32px' marginBottom='5px'>
              สิริวัฒน์ โชติเลอศักดิ์
            </Heading>
            <Text as='b' fontSize='2xl'>63070501073</Text>
          </Box>
          <Box sx={boxProfile} align="center" justify="center">
            <Image
              borderRadius='full'
              boxSize='200px'
              src='/image/sudarat2.jpg'
              minWidth='200px'
            />
            <Heading marginTop='32px' marginBottom='5px'>
              สุดารัตน์ ร่มสุข
            </Heading>
            <Text as='b' fontSize='2xl'>63070501076</Text>
          </Box>
        </Wrap>
      </Box>
    </div>
  );
}