import { Box, Button, Center, Flex, Grid, GridItem, Heading, Image, Text, Wrap } from '@chakra-ui/react';
import Head from "next/head";
import NextLink from "next/link";
import React from 'react';
import Colour from "../color/napalearncolor";
import Header from "../components/HeaderIndex.js";
import Hcomponent from "../components/HomeComponent.js";

export default function Index() {

  return (
    <div className="h-full flex items-center justify-center">
      <Head>
        <title>Nap A Learn Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>

      <Box sx={Hcomponent.bgColor} >
        <Header />
        <Flex align="center" justify="center">
          <Box sx={Hcomponent.container} align="center" justify="center">
            <Box sx={Hcomponent.container1} align="center" justify="center">
              <Box>
                <Image src='/image/Nap_a_learn_LOGO.png' />
              </Box>
              <Heading as='h2' size='2xl' marginBottom='40px' minWidth='400px'>
                ยินดีต้อนรับสู่ Nap a Learn
              </Heading>
              <Heading as='h2' size='xl' minWidth='400px'>
                งีบก่อน เรียนทีหลัง :-)
              </Heading>
            </Box>
            <Box sx={Hcomponent.boxText} align="center" justify="center">
              <Heading as='h2' size='xl' minWidth='200px'>
                “Nap a Learn” เป็นเว็บไซต์ที่มีจุดประสงค์เพื่อการศึกษาหาความรู้ ทั้งในทางปฏิบัติ และในทางความรู้ติดตัว นอกจากนั้นแล้ว ผู้ใช้เว็บไซต์ของพวกเรายังสามารถติดตามผลงานการเรียนรู้ต่างๆของตนเอง เพื่อประสิทธิภาพที่ดีที่สุดของการเรียนอีกด้วย</Heading>
            </Box>
            <Center>
              <NextLink href="/login" passHref>
                <Button colorScheme='white' size='lg' backgroundColor={Colour.FirstPink} marginTop='40px' marginBottom='20px' _hover={{
                  bg: 'White',
                  border: '2px solid',
                  color: Colour.FirstPink
                }}> มาเริ่มกันเลย ! </Button>
              </NextLink>
            </Center>
          </Box>
        </Flex>

        <Flex align="center" justify="center">
          <Box align="center" justify="center">
            <Box><Image src='/image/bear.png' width={300} height={300} /></Box>
            <Box><Heading as='h2' size='xl' marginTop='12px' marginBottom='12px' color='#3E3C6E'>
              มาดูกันว่า
            </Heading></Box>
            <Box><Heading as='h2' size='xl' marginBottom='60px' color='#3E3C6E'>
              Nap a Learn ทำอะไรได้บ้าง?
            </Heading></Box>
          </Box>
        </Flex>

        <Wrap spacing="30px" justify="center">
          <Flex sx={Hcomponent.boxContent}>
            <Box align="center" justify="center">
              <Box>
                <Image marginBottom='20px' src='/image/QuestionaireMini.png' />
                <Text sx={Hcomponent.informationHeadingText}> Questionaire</Text>
              </Box>
              <Flex sx={Hcomponent.boxContent1}>
                <Text sx={Hcomponent.informationText}>“Questionaire” เป็นฟีเจอร์์ที่ถูกจัดทำขึ้นเพื่อเป็นแบบ
                  ทดสอบความพิการของผู้ใช้งาน เช่น ผู้พิการทางด้านสมองหรือผู้พิการ
                  ออทิสติค เป็นต้น เมื่อทำแบบสอบถามเสร็จเรียบร้อยแล้ว ระบบจะทำการประเมินว่าผู้ใช้งานเว็บไซต์นั้นเข้าข่ายความพิการด้านไหน
                  และเว็บไซต์จะนำความพิการนั้นไปปรับเนื้อหาการเรียนรู้ให้เหมาะสมกับผู้ใช้งานต่อไป</Text>
              </Flex>
            </Box>
          </Flex>

          <Flex sx={Hcomponent.boxContent}>
            <Box align="center" justify="center">
              <Box>
                <Image marginBottom='20px' src='/image/LearningMaterialMini.png' />
                <Text sx={Hcomponent.informationHeadingText}> Learning Materials</Text>
              </Box>
              <Flex sx={Hcomponent.boxContent1}>
                <Text sx={Hcomponent.informationText}> “Learning Materials” เป็นฟีเจอร์ ที่ถูกจัดทำขึ้นเพื่อเสริมสร้างการเรียนรู้ของผู้ใช้งาน โดยจะแบ่งส่วนของฟีเจอร์ออกเป็นสอง
                  ส่วนซึ่งก็คือ article และ material ซึ่งในส่วนของ article จะเป็นบทความเกี่ยวกับความรู้ต่างๆ เช่น วิธีการปรับบุคลิกภาพ เป็นต้น
                  ในส่วนของ material จะเป็นรูปแบบการเรียนรู้ที่มีปฏิสัมพันธ์กับสิ่งที่เรียน เช่น การเล่นเกมปลูกผัก เพื่อให้ได้ความรู้การทำสวน เป็นต้น</Text>
              </Flex>
            </Box>
          </Flex>

          <Flex sx={Hcomponent.boxContent}>
            <Box align="center" justify="center">
              <Box>
                <Image marginBottom='20px' src='/image/ProfessionalSkillMini.png' />
                <Text sx={Hcomponent.informationHeadingText}> Professional Skills</Text>
              </Box>
              <Flex sx={Hcomponent.boxContent1}>
                <Text sx={Hcomponent.informationText}> “Professional Skills” เป็นฟีเจอร์ ที่ถูกจัดทำขึ้นเพื่อเสริมสร้างการเรียนรู้ในรูปแบบของวิชาชีพ โดยจะแบ่งส่วนของฟีเจอร์ออกเป็น
                  สองส่วนซึ่งก็คือ article และ workshop ซึ่งในส่วนของ article จะเป็นบทความเกี่ยวกับการเรียนรู้ที่เกี่ยวกับวิชาชีพ เช่น การปลูกผัก
                  เป็นต้น ในส่วนของ workshop จะเป็นคลิป หรือ วิธีทำให้ทำตาม เช่น การผัดข้าวผัด เป็นต้น</Text>
              </Flex>
            </Box>
          </Flex>

          <Flex sx={Hcomponent.boxContent}>
            <Box align="center" justify="center">
              <Box>
                <Image marginBottom='20px' src='/image/MusicTherapyMini.png' />
                <Text sx={Hcomponent.informationHeadingText}>  Music Therapy</Text>
              </Box>
              <Flex sx={Hcomponent.boxContent1}>
                <Text sx={Hcomponent.informationText}>  “Music Therapy” เป็นฟีเจอร์ ที่ถูกจัดทำขึ้นเพื่อเสริมสร้างความรู้สึกของผู้ใช้งาน ให้เกิดอารมณ์สุนทรีย์ และผ่อนคลายมากขึ้น
                  นอกจากนั้นผู้ใช้งานยังสามารถเล่นดนตรี ตามแบบฝึกหัดง่ายๆ ที่มีอยู่ในเว็บไซต์อีกด้วย โดยเครื่องดนตรีจะมีให้เลือกอย่างหลากหลาย
                  เช่น กลอง กีตาร์ เป็นต้น</Text>
              </Flex>
            </Box>
          </Flex>
        </Wrap>


        <Box sx={Hcomponent.container} align="center" justify="center">
          <Heading marginTop='48px' color='#3E3C6E' > มาพัฒนาตัวเองไปกับพวกเรา! </Heading>
          <Box marginTop='60px'>
            <Image src='/image/workshop.png' width={1200} />
          </Box>
        </Box>

        <Box sx={Hcomponent.container} align="center" justify="center">
          <Heading marginTop='48px' marginBottom='48px' color='black' > ทีมผู้จัดทำ </Heading>
        </Box>

        <Wrap spacing="30px" justify="center" marginBottom='60px'>
          <Box sx={Hcomponent.boxProfile} align="center" justify="center">
            <Image Image sx ={Hcomponent.devImage}
              src='/image/witchayut.jpg'
            />
            <Heading sx={Hcomponent.devHeading}>
              วิชยุฒม์ ช่วยชูกูล
            </Heading>
            <Text sx = {Hcomponent.devText}>63070501057</Text>
          </Box>
          <Box sx={Hcomponent.boxProfile} align="center" justify="center">
            <Image Image sx ={Hcomponent.devImage}
              src='/image/sirawit2.jpg'
            />
            <Heading sx={Hcomponent.devHeading}>
              สิรวิชญ์ วัฒโน
            </Heading>
            <Text sx = {Hcomponent.devText}>63070501071</Text>
          </Box>
          <Box sx={Hcomponent.boxProfile} align="center" justify="center">
            <Image Image sx ={Hcomponent.devImage}
              src='/image/siriwat2.jpg'
            />
            <Heading sx = {Hcomponent.devHeading}>
              สิริวัฒน์ โชติเลอศักดิ์
            </Heading>
            <Text sx = {Hcomponent.devText}>63070501073</Text>
          </Box>
          <Box sx={Hcomponent.boxProfile} align="center" justify="center">
            <Image sx ={Hcomponent.devImage}
              src='/image/sudarat2.jpg'
            />
            <Heading sx={Hcomponent.devHeading}>
              สุดารัตน์ ร่มสุข
            </Heading>
            <Text sx = {Hcomponent.devText}>63070501076</Text>
          </Box>

        </Wrap>
      </Box>
    </div>
  );
}